# profiles.yml (dbt_ecommerce klasörünün KÖKÜNDE olmalı)
ecommerce_dbt:
  outputs:
    trino:
      type: trino
      method: http
      user: trino
      catalog: iceberg
      host: trino-coordinator
      port: 8080
      schema: bronze
      threads: 3
      # Trino için gerekli ek ayarlar
      timezone: UTC
      retries: 3
  target: trino